// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaxcI2LW45VLUwR_3nwpiYMrGTNY-BqHI',
    appId: '1:583626070952:web:2472dc5e38a1f2c6d1db9d',
    messagingSenderId: '583626070952',
    projectId: 'inst-helper-pro',
    authDomain: 'inst-helper-pro.firebaseapp.com',
    storageBucket: 'inst-helper-pro.appspot.com',
    measurementId: 'G-LG067ZW4QF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3tR0IOcQT9qBi4jiKu7LU_H_rAefaUN0',
    appId: '1:583626070952:android:373bdfc05e8935eed1db9d',
    messagingSenderId: '583626070952',
    projectId: 'inst-helper-pro',
    storageBucket: 'inst-helper-pro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMv6wSGN72-3l8L_SBdC0DpHlDspi428A',
    appId: '1:583626070952:ios:cd96457dae71a22bd1db9d',
    messagingSenderId: '583626070952',
    projectId: 'inst-helper-pro',
    storageBucket: 'inst-helper-pro.appspot.com',
    iosBundleId: 'com.quantumweft.insthelper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMv6wSGN72-3l8L_SBdC0DpHlDspi428A',
    appId: '1:583626070952:ios:cd96457dae71a22bd1db9d',
    messagingSenderId: '583626070952',
    projectId: 'inst-helper-pro',
    storageBucket: 'inst-helper-pro.appspot.com',
    iosBundleId: 'com.quantumweft.insthelper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaxcI2LW45VLUwR_3nwpiYMrGTNY-BqHI',
    appId: '1:583626070952:web:4c6bbe73c85167b6d1db9d',
    messagingSenderId: '583626070952',
    projectId: 'inst-helper-pro',
    authDomain: 'inst-helper-pro.firebaseapp.com',
    storageBucket: 'inst-helper-pro.appspot.com',
    measurementId: 'G-3RXQXTHVJZ',
  );
}
